# An environment file for Project Officers wanted to use Conda rather than
# virtualenv
# conda env create --file=environment.yml
# conda env update --file=environment.yml
name: data_services_3.8
channels:
  - conda-forge
  - defaults
dependencies:
  - freetype
  - libpng
  - pkg-config
  - python=3.8
  - pip>=20.0.2
  - numpy
  - awscli
  - boto3
  - udunits2
  - pytest
  - gdal
  - pip:
      - -r requirements.txt
      - -c constraints.txt
      - "git+https://github.com/aodn/cc-plugin-imos.git"
